---
abstract: 'Because some things never die'
author:
  - 'Pedro Melo, C<< <melo at cpan.org> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Rasputine
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/melo/rasputine
version: 0.01
